steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.api'
      - '-t'
      - '${_IMAGE_NAME}:${_VERSION}'
      - '-t'
      - '${_IMAGE_NAME}:latest'
      - '--build-arg'
      - 'VERSION=${_VERSION}'
      - '--build-arg'
      - 'COMMIT_SHA=${_COMMIT_SHA}'
      - '.'

  # Push the versioned image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_NAME}:${_VERSION}'

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_NAME}:latest'

substitutions:
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/yc-partners/callie-integrations/callie-api'
  _VERSION: 'latest'
  _COMMIT_SHA: 'unknown'

options:
  machineType: 'E2_HIGHCPU_8' 